# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Game
minecraft_version = 1.21.1
yarn_mappings = 1.21.1+build.1
minecraft_compat_version=1.21

# Loader
fabric_loader_version = 0.16.9
neoforge_version = 21.1.201
yarn_mappings_patch_neoforge_version = 1.21+build.4

# Mod
mod_version=3.6.3
maven_group = net.dungeon_difficulty
archives_name = dungeon_difficulty
enabled_platforms = fabric,neoforge

# Dependencies
fabric_api_version = 0.115.6+1.21.1
forgified_fabric_api_version=0.115.6+2.1.1+1.21.1
tiny_config_version=3.0.0